# Compose for local development
---
services:

  service:
    build:
      cache_from:
        - ghcr.io/damienallen/bosmapper-service:latest
      context: .
      target: service
    restart: unless-stopped
    environment:
      - MASTER_TOKEN=dev_token
    volumes:
      - ./app:/app
    ports:
      - "8080:8888"
    depends_on:
      - mongo

  ui:
    build:
      cache_from:
        - ghcr.io/damienallen/bosmapper-static:latest
      context: .
      dockerfile: Dockerfile
      target: static
    ports:
      - "3000:3080"

  mongo:
    image: mongo:8.2-noble
    restart: always
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017

volumes:
  mongo-data:
