# Compose for local development

---
version: "3.6"
services:

  bosmapper:
    build:
      cache_from:
        - ghcr.io/damienallen/bosmapper/server:main
      context: .
      target: development
    restart: unless-stopped
    command: ["/start-reload.sh"]
    environment:
      - MASTER_TOKEN=dev_token
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    depends_on:
      - mongo
      
  static:
    build:
      context: .
      dockerfile: Dockerfile
      target: static

  mongo:
    image: mongo:latest
    restart: unless-stopped
    command: mongod
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017



volumes:
  mongo-data: