# Compose for local development
---
services:

  service:
    build:
      cache_from:
        - ghcr.io/damienallen/bosmapper-service:latest
      context: .
      target: service
    restart: unless-stopped
    command: ["/start-reload.sh"]
    environment:
      - MASTER_TOKEN=dev_token
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    depends_on:
      - mongo
      
  ui:
    build:
      cache_from:
        - ghcr.io/damienallen/bosmapper-static:latest
      context: .
      dockerfile: Dockerfile
      target: static

  mongo:
    image: mongo:latest
    restart: unless-stopped
    command: mongod
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017

volumes:
  mongo-data: