name: Build Images

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      IMAGE_NAME: bosmapper_server
      REGISTRY_URL: docker.pkg.github.com/damienallen/bosmapper/server
      TAG: main

    steps:
      - uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build 'bosmapper-service'
        uses: docker/build-push-action@v6
        with:
          push: true
          target: service
          tags: ghcr.io/damienallen/bosmapper-service:latest
          cache-from: type=registry,ref=ghcr.io/damienallen/bosmapper-service:latest
          cache-to: type=inline

      - name: Build 'bosmapper-static'
        uses: docker/build-push-action@v6
        with:
          push: true
          target: static
          tags: ghcr.io/damienallen/bosmapper-static:latest
          cache-from: type=registry,ref=ghcr.io/damienallen/bosmapper-static:latest
          cache-to: type=inline

  push-tag:
    name: Push Tag
    runs-on: ubuntu-24.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-tag and push 'bosmapper-service' with tag
        uses: docker/build-push-action@v6
        with:
          push: true
          target: service
          tags: ghcr.io/damienallen/bosmapper-service:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/damienallen/bosmapper-service:latest

      - name: Re-tag and push 'bosmapper-static' with tag
        uses: docker/build-push-action@v6
        with:
          push: true
          target: static
          tags: ghcr.io/damienallen/bosmapper-static:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/damienallen/bosmapper-static:latest
